version: "2"
services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    links:
      - db
    env_file:
      - "./.env.web"
    depends_on:
      - db

  dbdata:
    image: "library/mysql:5.7"
    volumes:
      - /var/lib/mysql
    command: "true"

  db:
    image: "library/mysql:5.7"
    ports:
      - "3306:3306"
    env_file:
      - "./.env.db"
    volumes_from:
      - dbdata
